eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    instance:
      hostname: discovery-server
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
spring:
  kafka:
    bootstrap-servers: broker:29092