server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    instance:
      hostname: discovery-server
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
