spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: product-service
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    instance:
      hostname: discovery-server
server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0
