spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus